### PR TITLE
Add xio_gdal_handler

### LINKED ISSUE #132: Support GDAL Virtual File Systems
Supporting [GDAL Virtual File Systems](https://gdal.org/user/virtual_file_systems.html) would allow xtensor to access files located in compressed archives (zip, tar), on the network (http, https, ftp), and in the cloud (AWS S3, Google Cloud Storage, Microsoft Azure, Alibaba Cloud OSS, OpenStack Swift Object Storage, Hadoop File System), and more (standard I/O, in-memory, etc.).
The [GDAL API](https://gdal.org/doxygen/cpl__vsi_8h.html) uses C `FILE`-like objects, not streams as in our IO handlers, so I guess we should also provide dump/load functions that operate on such objects.
This is part of an effort to implement a Zarr driver in GDAL using xtensor-zarr.

### PR DESCRIPTION
**Pull request by davidbrochart**
In addition to stream-like objects, this PR gives support for FILE-like objects to format handlers.
This first commit only changes the `xio_binary` format. I'll update the other formats after review.
See #132.

### CODE REVIEW

**Comment by davidbrochart** [comment]
Now the `file` and `vsilfile` classes are pretty close to a stream. I think we should just have a "wrapper" class for file-like objects and stream-like objects, that should implement these common methods:
- `read(std::string& buffer)`
- `write(std::string& buffer, std::size_t size)`
And get rid of the "overload" `dump_bin_imp` and `load_bin_imp` functions.

**Comment by davidbrochart** [comment]
The stream and file wrapper classes implement the methods needed in the compression formats that we currently have, so they are compatible with a stream or a file type.
If a future compression format needs a proper stream or file object (not our wrapper), we could specialize the load/dump functions for this particular type (e.g. stream) and get the object from our wrapper, and throw an "unsupported format" for the other type (e.g. file), like "GDAL doesn't support this format (because GDAL is a file-based IO handler, and the format is stream-based)".
This is the best I can think of, since wrapping a file into a stream doesn't seem to be a trivial task.

**Comment by davidbrochart** [comment]
Not sure about the name `xio_gdal_handler`. [GDAL's documentation](https://gdal.org/user/virtual_file_systems.html) talks about Virtual File System, and [the functions](https://gdal.org/doxygen/cpl__vsi_8h.html) are called VSI functions. But neither `xio_vfs_handler` or `xio_vsi_handler` sound good to me.

**Comment by JohanMabille** [comment]
LGTM!

I could be nicve to do a pass on API homogeneity, but this can be done in a dedicated PR!

**Pull request merged**
